services:
  - type: web
    name: showyourwork-backend
    env: node
    repo:
      url: https://github.com/kinman1313/showyourwork
      branch: feature/family-management
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /test-env
    autoDeploy: true

  - type: static
    name: showyourwork-frontend
    repo:
      url: https://github.com/kinman1313/showyourwork
      branch: feature/family-management
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true 