services:
  - type: web
    name: showyourwork-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://showyourwork-frontend.onrender.com
      - key: PORT
        value: 5000
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://showyourwork-frontend.onrender.com
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET,POST,PUT,DELETE,PATCH,OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type,Authorization
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
    healthCheckPath: /test-env
    autoDeploy: true

  - type: static
    name: showyourwork-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://showyourwork-backend.onrender.com
      - key: NODE_ENV
        value: production
      - key: REACT_APP_ENV
        value: production
      - key: GENERATE_SOURCEMAP
        value: "false"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true 